# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 62709c7278f6af4810ddcba54b54e7434484ce16f62b885ad2d1681679fc209bfe26ddcfe215a7bcba7d1d41f241b8bd377954ddea52d9c750d52f9760e4b254

test:
  secret_key_base: 0d741125c7ec7a1d58c80cb431a962fefad07eaf178c87cdd831918a4ccce2f3ee64629fe42a5560f5cfb839d9983909f7e07180c4a1cc78fe060eba000fb5cb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
